-- ============================================
-- Argos - PostgreSQL Schema
-- Tech watch and intelligence platform
-- Version: 1.0.0
-- ============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================
-- TABLE: workspaces
-- Multi-tenant isolation
-- ============================================
CREATE TABLE IF NOT EXISTS workspaces (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    domain VARCHAR(50),
    icon VARCHAR(50) DEFAULT 'globe',
    color VARCHAR(7) DEFAULT '#6366f1',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workspaces_slug ON workspaces(slug);
CREATE INDEX idx_workspaces_active ON workspaces(is_active);

INSERT INTO workspaces (name, slug, description, domain) VALUES
    ('Default', 'default', 'Default workspace', 'general')
ON CONFLICT (slug) DO NOTHING;

-- ============================================
-- TABLE: sources
-- Watched URLs and RSS/API sources
-- ============================================
CREATE TABLE IF NOT EXISTS sources (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url TEXT NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('rss', 'website', 'github', 'api')),
    category VARCHAR(100),
    description TEXT,
    tags TEXT[],
    active BOOLEAN DEFAULT TRUE,
    workspace_id INTEGER REFERENCES workspaces(id) ON DELETE SET NULL,
    -- Watch monitoring (hash-based change detection)
    content_hash VARCHAR(64),
    last_checked_at TIMESTAMP WITH TIME ZONE,
    check_interval_minutes INTEGER DEFAULT 60 CHECK (check_interval_minutes >= 5),
    monitor_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sources_type ON sources(type);
CREATE INDEX idx_sources_active ON sources(active);
CREATE INDEX idx_sources_workspace ON sources(workspace_id);
CREATE INDEX idx_sources_monitor ON sources(monitor_enabled) WHERE monitor_enabled = TRUE;

-- ============================================
-- TABLE: items
-- Scraped/collected web content
-- ============================================
CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    -- Origin
    source_type VARCHAR(50) NOT NULL CHECK (source_type IN ('rss', 'github', 'website', 'api', 'browse', 'search', 'manual')),
    source_url TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    -- Content
    title VARCHAR(500) NOT NULL,
    summary TEXT,
    author VARCHAR(255),
    published_at TIMESTAMP WITH TIME ZONE,
    -- Classification
    importance VARCHAR(20) CHECK (importance IN ('critical', 'high', 'medium', 'low')),
    item_type VARCHAR(20) CHECK (item_type IN ('news', 'research', 'tutorial', 'tool', 'discussion', 'other')),
    keywords TEXT[],
    classification_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (classification_status IN ('pending', 'classified', 'rejected')),
    -- Digest (generated by LLM)
    digest_markdown TEXT,
    digest_json JSONB,
    digest_generated_at TIMESTAMP WITH TIME ZONE,
    -- RAG indexing
    rag_indexed BOOLEAN DEFAULT FALSE,
    rag_indexed_at TIMESTAMP WITH TIME ZONE,
    -- Multi-tenant
    workspace_id INTEGER REFERENCES workspaces(id) ON DELETE SET NULL,
    sujet_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX items_url_sujet_key ON items (url, COALESCE(sujet_id, -1));
CREATE INDEX idx_items_classification_status ON items(classification_status);
CREATE INDEX idx_items_source_type ON items(source_type);
CREATE INDEX idx_items_importance ON items(importance);
CREATE INDEX idx_items_item_type ON items(item_type);
CREATE INDEX idx_items_keywords ON items USING GIN(keywords);
CREATE INDEX idx_items_title_trgm ON items USING GIN(title gin_trgm_ops);
CREATE INDEX idx_items_created_at ON items(created_at DESC);
CREATE INDEX idx_items_workspace ON items(workspace_id);
CREATE INDEX idx_items_rag_indexed ON items(rag_indexed);

-- ============================================
-- TABLE: topics
-- Classification taxonomy
-- ============================================
CREATE TABLE IF NOT EXISTS topics (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    parent_id INTEGER REFERENCES topics(id) ON DELETE SET NULL,
    item_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_topics_slug ON topics(slug);

INSERT INTO topics (name, slug, description) VALUES
    ('AI / LLM', 'ai-llm', 'Artificial intelligence and large language models'),
    ('MCP', 'mcp', 'Model Context Protocol'),
    ('Web', 'web', 'Web development and browser technologies'),
    ('Security', 'security', 'Cybersecurity and privacy'),
    ('Data', 'data', 'Data engineering and analytics'),
    ('Open Source', 'open-source', 'Open source projects and tools'),
    ('Other', 'other', 'Other topics')
ON CONFLICT (slug) DO NOTHING;

-- ============================================
-- TABLE: items_topics (M2M)
-- ============================================
CREATE TABLE IF NOT EXISTS items_topics (
    item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, topic_id)
);

CREATE INDEX idx_items_topics_topic ON items_topics(topic_id);

-- ============================================
-- TABLE: browse_sessions
-- Log of web.browse() calls
-- ============================================
CREATE TABLE IF NOT EXISTS browse_sessions (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('success', 'error', 'timeout')),
    -- Extracted content
    title VARCHAR(500),
    content_text TEXT,
    content_length INTEGER,
    links_found INTEGER DEFAULT 0,
    -- Performance
    duration_ms INTEGER,
    engine VARCHAR(20) DEFAULT 'playwright' CHECK (engine IN ('playwright', 'requests')),
    -- Context
    workspace_id INTEGER REFERENCES workspaces(id) ON DELETE SET NULL,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_browse_sessions_url ON browse_sessions USING GIN(url gin_trgm_ops);
CREATE INDEX idx_browse_sessions_created_at ON browse_sessions(created_at DESC);
CREATE INDEX idx_browse_sessions_status ON browse_sessions(status);

-- ============================================
-- TABLE: search_sessions
-- Log of web.search() calls
-- ============================================
CREATE TABLE IF NOT EXISTS search_sessions (
    id SERIAL PRIMARY KEY,
    query TEXT NOT NULL,
    engine VARCHAR(20) DEFAULT 'duckduckgo',
    results_count INTEGER DEFAULT 0,
    results JSONB,
    duration_ms INTEGER,
    workspace_id INTEGER REFERENCES workspaces(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_search_sessions_created_at ON search_sessions(created_at DESC);
CREATE INDEX idx_search_sessions_query_trgm ON search_sessions USING GIN(query gin_trgm_ops);

-- ============================================
-- TABLE: rag_queries
-- RAG Q&A log + chatbot notice
-- ============================================
CREATE TABLE IF NOT EXISTS rag_queries (
    id SERIAL PRIMARY KEY,
    user_identifier VARCHAR(100) NOT NULL DEFAULT 'anonymous',
    query TEXT NOT NULL,
    answer TEXT NOT NULL,
    sources JSONB,
    confidence_score DECIMAL(3,2) CHECK (confidence_score BETWEEN 0 AND 1),
    was_helpful BOOLEAN,
    user_feedback TEXT,
    workspace_id INTEGER REFERENCES workspaces(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rag_queries_user ON rag_queries(user_identifier);
CREATE INDEX idx_rag_queries_created_at ON rag_queries(created_at DESC);
CREATE INDEX idx_rag_queries_query_trgm ON rag_queries USING GIN(query gin_trgm_ops);

-- ============================================
-- TABLE: llm_usage
-- LLM cost tracking
-- ============================================
CREATE TABLE IF NOT EXISTS llm_usage (
    id SERIAL PRIMARY KEY,
    operation_type VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50),
    entity_id INTEGER,
    model VARCHAR(100),
    tokens_used INTEGER,
    cost_usd NUMERIC(12,8),
    input_data JSONB,
    output_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_llm_usage_operation ON llm_usage(operation_type);
CREATE INDEX idx_llm_usage_created_at ON llm_usage(created_at DESC);

-- ============================================
-- TABLE: system_logs
-- ============================================
CREATE TABLE IF NOT EXISTS system_logs (
    id SERIAL PRIMARY KEY,
    level VARCHAR(20) NOT NULL CHECK (level IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')),
    component VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    context JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_system_logs_level ON system_logs(level);
CREATE INDEX idx_system_logs_component ON system_logs(component);
CREATE INDEX idx_system_logs_created_at ON system_logs(created_at DESC);

-- ============================================
-- TABLE: api_keys
-- ============================================
CREATE TABLE IF NOT EXISTS api_keys (
    id SERIAL PRIMARY KEY,
    key_hash VARCHAR(64) NOT NULL UNIQUE,
    key_prefix VARCHAR(8) NOT NULL,
    workspace_id INTEGER REFERENCES workspaces(id) ON DELETE CASCADE,
    permissions JSONB DEFAULT '["read"]',
    rate_limit_per_hour INTEGER DEFAULT 1000,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE
);

-- ============================================
-- TRIGGERS
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_items_updated_at BEFORE UPDATE ON items
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_topics_updated_at BEFORE UPDATE ON topics
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_workspaces_updated_at BEFORE UPDATE ON workspaces
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_sources_updated_at BEFORE UPDATE ON sources
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- DAILY BRIEFINGS
-- ============================================
CREATE TABLE IF NOT EXISTS daily_briefings (
    id                SERIAL PRIMARY KEY,
    briefing_date     DATE NOT NULL UNIQUE,
    executive_summary TEXT,
    top_items         JSONB DEFAULT '[]',
    trends            JSONB DEFAULT '[]',
    stats             JSONB DEFAULT '{}',
    workspace_id      INTEGER REFERENCES workspaces(id) ON DELETE SET NULL,
    tokens_used       INTEGER DEFAULT 0,
    cost_usd          NUMERIC(10, 6) DEFAULT 0,
    generated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_briefings_date ON daily_briefings (briefing_date DESC);

-- ============================================
-- VIEWS
-- ============================================
CREATE OR REPLACE VIEW pending_items_view AS
SELECT i.id, i.title, i.source_type, i.importance, i.keywords, i.created_at, i.url
FROM items i
WHERE i.classification_status = 'pending'
ORDER BY i.created_at DESC;

CREATE OR REPLACE VIEW unindexed_items_view AS
SELECT i.id, i.title, i.summary, i.digest_json, i.created_at
FROM items i
WHERE i.rag_indexed = FALSE
  AND i.classification_status = 'classified'
  AND i.digest_json IS NOT NULL
ORDER BY i.created_at DESC;

-- ============================================
-- INITIAL LOG
-- ============================================
INSERT INTO system_logs (level, component, event_type, message, context)
VALUES (
    'INFO', 'database', 'schema_initialized',
    'Argos database schema initialized',
    jsonb_build_object('version', '1.0.0', 'timestamp', CURRENT_TIMESTAMP)
);
